services:
  dockerlock:
    build:
      context: .
      dockerfile: Dockerfile
    # this pulls from a local docker build, not from dockerhub
    image: dockerlock
    container_name: dockerlock
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
