name: dockerlock
channels:
  - conda-forge
dependencies:
- altair
- conda-lock=>3.0.4
- jupyterlab
- pandas
- pandera
- pip
- pointblank
- python
- seaborn
# as of Dec 2025, conda has matplotlib=3.10.8, but only 3.10.7 is on pypi
- matplotlib=3.10.7
- pip:
  - deepchecks
  - vegafusion
